services:
  mongodb:
    image: mongo:latest
    container_name: tour-pakage-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    image: abdulraheem381/tour-package-cal-backend
    container_name: tour-pakage-backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/tour-pakage
      - PORT=3000
      - FRONTEND_URL=http://localhost:5173
      - JWT_SECRET=keyboard_cat_secret_change_me
    depends_on:
      - mongodb

  frontend:
    image: abdulraheem381/tour-package-cal-front
      args:
        - VITE_API_URL=http://localhost:3000/api/v1
    container_name: tour-pakage-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
